version: '3'

services:
  database:
    image: docker.io/mysql:8
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=s3cret
      - MYSQL_DATABASE=awir
      - MYSQL_USER=awir
      - MYSQL_PASSWORD=secret
