spring:
  datasource:
    username: awir
    password: secret
    url: jdbc::mysql://localhost:3306/awir
  thymeleaf:
    cache: false
  web:
    resources:
      chain:
        cache: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: a6b1e84b668085ff3f50
            client-secret: 54252e3ead995c70ad8240f75a9a6084bc1be024